[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"

[dev-dependencies]
assert_cmd = "2.0.14"
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
